---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
  # usually makes debugging easier, and sometimes half a codebook
  # is better than none
  echo = FALSE # don't show the R code
)
ggplot2::theme_set(ggplot2::theme_bw())
```

Here, we import data from formr

```{r}
library(hera)
```

But we can also import data from e.g. an SPSS file.
```{r message=FALSE, warning=FALSE}
vocab <- readr::read_csv(system.file("extdat",
  "data-flow/vocab.csv",
  package = "hera"
))
codebook_data <- vocab
```


Sometimes, the metadata is not set up in such a way that codebook
can leverage it fully. These functions help fix this.

```{r codebook}
library(codebook) # load the package
# omit the following lines, if your missing values are already properly labelled
codebook_data <- detect_missing(codebook_data,
  only_labelled = TRUE, # only labelled values are autodetected as
  # missing
  negative_values_are_missing = FALSE, # negative values are NOT missing values
  ninety_nine_problems = TRUE, # 99/999 are missing values, if they
  # are more than 5 MAD from the median
)

# If you are not using formr, the codebook package needs to guess which items
# form a scale. The following line finds item aggregates with names like this:
# scale = scale_1 + scale_2R + scale_3R
# identifying these aggregates allows the codebook function to
# automatically compute reliabilities.
# However, it will not reverse items automatically.
codebook_data <- detect_scales(codebook_data)
```

Now, generating a codebook is as simple as calling codebook from a chunk in an
rmarkdown document.

```{r}
codebook(codebook_data)
```
