---
title: "data-dictionary"
output:
  pdf_document: default
  word_document: default
  html_document: default
date: "2022-09-01"
editor_options:
  chunk_output_type: console
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(visNetwork)
```

# Data diagram

## High Level Data flows


```{r echo=FALSE, fig.height=3, fig.width=4, message=FALSE, warning=FALSE, results='asis'}

high_level_flows <- read_csv(system.file("extdat",
      "data-flow/high-level-flows.csv",
      package = "hera"
    ))

  nodes <- high_level_flows %>%
    select(label, group, level, shape) %>%
      unique() %>%
   na.omit() %>%
   rename("id" = label) 

visNetwork(nodes, high_level_flows, width = "100%") %>%
  visEdges(arrows = "to") %>%
  visNodes(
    shadow = list(enabled = TRUE, size = 10),
    size = 50
  ) %>%
  # visGroups(groupname = "question", color = "lightgreen") %>%
  # visGroups(groupname = "data_source", color = "lightblue") %>%
  # visLegend() %>%
  visOptions(highlightNearest = list(enabled = T, degree = 2, hover = T)) %>%
  visHierarchicalLayout(direction = "LR", levelSeparation = 150) %>%
  visOptions(highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = T) %>% 
   visInteraction(dragNodes = FALSE, 
                 dragView = FALSE, 
                 zoomView = FALSE) %>% 
  visExport(type = "png")


```

## Visual Survey

```{r echo=FALSE, fig.height=3, fig.width=4, message=FALSE, warning=FALSE}

high_level_flows <- read_csv("../inst/extdat/data-flow/high-level-flows.csv" )

high_level_flows <- high_level_flows %>% 
  filter(assessment == "visual survey")


  nodes <- high_level_flows %>%
    select(label, group, level, shape) %>%
      unique() %>%
   na.omit() %>%
   rename("id" = label) 

visNetwork(nodes, high_level_flows, width = "100%") %>%
  visEdges(arrows = "to") %>%
  visNodes(
    shadow = list(enabled = TRUE, size = 10),
    size = 50
  ) %>%
  # visGroups(groupname = "question", color = "lightgreen") %>%
  # visGroups(groupname = "data_source", color = "lightblue") %>%
  # visLegend() %>%
  visOptions(highlightNearest = list(enabled = T, degree = 2, hover = T)) %>%
  visHierarchicalLayout(direction = "LR", levelSeparation = 150) %>%
  visOptions(highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = T)


```

### eDNA Benthic

```{r fig.height=3, fig.width=4, message=FALSE, warning=FALSE}

high_level_flows <- read_csv("../inst/extdat/data-flow/high-level-flows.csv" )


high_level_flows <- high_level_flows %>% 
  filter(assessment == "Benthic Marine eDNA")


  nodes <- high_level_flows %>%
    select(label, group, level, shape) %>%
      unique() %>%
   na.omit() %>%
   rename("id" = label) 

visNetwork(nodes, high_level_flows, width = "100%") %>%
  visEdges(arrows = "to") %>%
  visNodes(
    shadow = list(enabled = TRUE, size = 10),
    size = 50
  ) %>%
  # visGroups(groupname = "question", color = "lightgreen") %>%
  # visGroups(groupname = "data_source", color = "lightblue") %>%
  # visLegend() %>%
  visOptions(highlightNearest = list(enabled = T, degree = 2, hover = T)) %>%
  visHierarchicalLayout(direction = "LR", levelSeparation = 150) %>%
  visOptions(highlightNearest = list(enabled = T, hover = T),
             nodesIdSelection = T)


```

