---
title: "Regulatory Catalogue"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Regulatory Catalogue}
  %\VignetteEncoding{UTF-8}  
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hera)
library(dplyr)
library(purrr)
library(tidyr)
library(magrittr)
library(kableExtra)
library(slickR)
library(visNetwork)
```

## Assessments

```{r assessment-carousel, echo=FALSE}

data <- bind_rows(catalogue$data)
data <- filter(data, question == "name_short")

dt_url <- paste0(gsub(" ", "-", tolower(trimws(data$response))), ".html")

slickR::slickR(
  list.files("images", full.names = TRUE, pattern = "png"),
  objLinks = dt_url[1:2],
  height = 200,
  width = "95%"
)
```

  

```{r assessments, echo=FALSE}

data <- bind_rows(catalogue$data)
data <- filter(data, question == "name_short")
dt_url <- paste0(gsub(" ", "-", tolower(trimws(data$response))), ".html")

data <- bind_rows(catalogue$data)
data <- filter(data, question == "name_long")
data %>%
  mutate(name = cell_spec(response, "html", link = dt_url)) %>%
  select(name) %>% 
  kable(format = "html", escape = FALSE) %>%
  kable_styling(bootstrap_options = c("hover", "condensed"))
```

## Reports

```{r reports, echo=FALSE, warning=FALSE}

# reports <- catalogue$reports %>%
#   bind_rows() %>%
#   unique()
# kable(reports, format = "html", escape = FALSE) %>%
#   kable_styling(bootstrap_options = c("hover", "condensed"))
```

## Dependencies

```{r dependencies, echo=FALSE}
# nodes <- catalogue %>%
#   select(assessment) %>%
#   rename("id" = assessment) %>%
#   mutate(
#     "label" = id,
#     group = "Assessment",
#     "level" = 2
#   )
# 
# nodes <- catalogue$questions %>%
#   bind_rows() %>%
#   select(question) %>%
#   unique() %>%
#   na.omit() %>%
#   rename("id" = question) %>%
#   mutate(
#     "label" = id,
#     group = "Question",
#     "level" = 1
#   ) %>%
#   bind_rows(nodes)
# 
# 
#  predictors <- unnest(select(catalogue, predictors, assessment),
#                  c(predictors, assessment)) %>%
#    bind_rows() %>% 
#    mutate(across(names(.), as.character)) %>% 
#    pivot_longer(cols = -assessment, 
#                 names_to = "question") %>% 
#    filter(!is.na(value)) %>% 
#    select(question, assessment) 
#  
#    nodes <- predictors %>% 
#     select(question) %>% 
#       unique() %>%
#    na.omit() %>%
#    rename("id" = question) %>%
#    mutate(
#      "label" = id,
#    group = "Question",
#      "level" = 1
#    ) %>%
#    bind_rows(nodes)
# 
# 
# questions <- catalogue$questions %>%
#   bind_rows() %>%
#   select(question) %>%
#   na.omit()
# 
# questions <- predictors %>%
#      select(question) %>% 
#   bind_rows(questions)
# 
# assessments <- catalogue %>% 
#   select(assessment) %>% 
#   filter(assessment != "rict")
# 
# assessments <- predictors %>%
#      select(assessment) %>% 
#   bind_rows(assessments)
# 
# edges <- data.frame(
#   "from" = unlist(questions$question),
#   "to" = unlist(assessments$assessment)
# )
# 
# visNetwork(nodes, edges, width = "100%") %>%
#   visEdges(arrows = "to") %>%
#   visNodes(
#     shadow = list(enabled = TRUE, size = 10),
#     size = 50
#   ) %>%
#   visGroups(groupname = "Question", color = "lightgreen") %>%
#   visGroups(groupname = "Assessment", color = "lightblue") %>%
#   visLegend() %>%
#   visOptions(highlightNearest = list(enabled = T, degree = 2, hover = T)) %>%
#   visHierarchicalLayout(direction = "LR", levelSeparation = 150) %>%
#   visOptions(highlightNearest = list(enabled = T, hover = T), 
#              nodesIdSelection = T)
#   


```
